# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
   config.vm.provider "virtualbox" do |vb|
     vb.memory = "8192"
     config.ssh.forward_x11 = true
     config.ssh.forward_agent = true
     config.vm.provision :shell, path: "bootstrap.sh"
   end
end
